vulnerabilities:
  - id: CVE-2025-66516
    paths:
      - opt/apache-jmeter-5.6.3/lib/tika-core-1.28.5.jar
      - opt/apache-jmeter-5.6.3/lib/tika-parsers-1.28.5.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2024-47072
    paths:
      - opt/apache-jmeter-5.6.3/lib/xstream-1.4.20.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2024-25638
    paths:
      - opt/apache-jmeter-5.6.3/lib/dnsjava-2.1.9.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2025-24970
    paths:
      - opt/apache-jmeter-5.6.3/lib/neo4j-java-driver-4.4.13.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2024-57699
    paths:
      - opt/apache-jmeter-5.6.3/lib/json-smart-2.5.0.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2025-54988
    paths:
      - opt/apache-jmeter-5.6.3/lib/tika-parsers-1.28.5.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2022-44729
    paths:
      - opt/apache-jmeter-5.6.3/lib/batik-bridge-1.16.jar
      - opt/apache-jmeter-5.6.3/lib/batik-transcoder-1.16.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2026-42583
    paths:
      - opt/apache-jmeter-5.6.3/lib/neo4j-java-driver-4.4.13.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2026-44249
    paths:
      - opt/apache-jmeter-5.6.3/lib/neo4j-java-driver-4.4.13.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2026-45416
    paths:
      - opt/apache-jmeter-5.6.3/lib/neo4j-java-driver-4.4.13.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2026-50010
    paths:
      - opt/apache-jmeter-5.6.3/lib/neo4j-java-driver-4.4.13.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2026-54512
    paths:
      - home/steadybit/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.21.3/jackson-databind-2.21.3.jar
      - opt/apache-jmeter-5.6.3/lib/jackson-databind-2.16.1.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: CVE-2026-54513
    paths:
      - home/steadybit/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.21.3/jackson-databind-2.21.3.jar
      - opt/apache-jmeter-5.6.3/lib/jackson-databind-2.16.1.jar
    statement: Wait for a new JMeter-Release
    expired_at: 2026-09-01
  - id: GHSA-r7wm-3cxj-wff9
    statement: Waiting for debian upstream fix
    expired_at: 2026-09-01
